begin;
do $$ begin perform set_config('votus_projections_down.workspace_query_owner',pg_has_role(current_user,'workspace_query_owner','SET')::text,true); if not pg_has_role(current_user,'workspace_query_owner','SET') then execute format('grant workspace_query_owner to %I',current_user); end if; end $$;
set role workspace_query_owner;
drop function workspace_api.official_provenance(uuid,uuid,text,text);
drop function workspace_api.official_reference(uuid,uuid,text,text);
drop function workspace_api.official_schools(uuid,uuid,text,text);
reset role;
drop policy workspace_query_owner_archive_entry_select on public.archive_entry;
revoke select on public.archive_entry from workspace_query_owner;
revoke execute on function public.results_exploration_schools(uuid,uuid,text,text) from workspace_query_owner;
do $$ begin if current_setting('votus_projections_down.workspace_query_owner',true)='false' then execute format('revoke workspace_query_owner from %I',current_user); end if; end $$;
commit;
