begin;
do $$ begin perform set_config('votus_drilldown_facets.workspace_query_owner',pg_has_role(current_user,'workspace_query_owner','SET')::text,true); if not pg_has_role(current_user,'workspace_query_owner','SET') then execute format('grant workspace_query_owner to %I',current_user); end if; end $$;
grant create on schema workspace_api to workspace_query_owner;
set role workspace_query_owner;
create or replace function workspace_api.official_facets(
 p_election_id uuid default null,p_category_id uuid default null,p_distrito_code text default null,
 p_seccion_code text default null,p_circuito_code text default null,p_establecimiento_code text default null
) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,workspace_private,pg_temp as $$
declare auth_status text; scope_districts text[]; scope_sections text[]; non_official_total bigint:=0; incomplete_lineage_total bigint:=0; facet_total bigint:=0; circuit_total bigint:=0; establishment_total bigint:=0; mesa_total bigint:=0; facet_page jsonb:='[]'; circuit_page jsonb:='[]'; establishment_page jsonb:='[]'; mesa_page jsonb:='[]'; exclusions jsonb:='[]'; overflow_exclusions jsonb:='[]';
begin
 select min(a.authorization_status),array_agg(a.distrito_code order by a.distrito_code,a.seccion_code) filter(where a.distrito_code is not null),array_agg(a.seccion_code order by a.distrito_code,a.seccion_code) filter(where a.seccion_code is not null) into auth_status,scope_districts,scope_sections from workspace_private.authorized_section_scopes() a;
 if auth_status not in ('authorized','authorized_empty') then return jsonb_build_object('status',auth_status,'facets','[]'::jsonb,'total',0,'truncated',false,'circuitos','[]'::jsonb,'establecimientos','[]'::jsonb,'mesas','[]'::jsonb,'exclusions','[]'::jsonb); end if;
 if auth_status='authorized_empty' then return jsonb_build_object('status','ok','facets','[]'::jsonb,'total',0,'truncated',false,'circuitos','[]'::jsonb,'establecimientos','[]'::jsonb,'mesas','[]'::jsonb,'exclusions','[]'::jsonb); end if;
 if (p_category_id is not null and p_election_id is null) or (p_distrito_code is not null and p_category_id is null) or (p_seccion_code is not null and p_distrito_code is null) or (p_circuito_code is not null and p_seccion_code is null) or (p_establecimiento_code is not null and p_circuito_code is null) or (p_distrito_code is not null and not exists(select 1 from unnest(scope_districts) d(code) where d.code=p_distrito_code)) or (p_seccion_code is not null and not exists(select 1 from unnest(scope_districts,scope_sections) s(distrito_code,seccion_code) where (s.distrito_code,s.seccion_code)=(p_distrito_code,p_seccion_code))) then return jsonb_build_object('status','selection_invalid','facets','[]'::jsonb,'total',0,'truncated',false,'circuitos','[]'::jsonb,'establecimientos','[]'::jsonb,'mesas','[]'::jsonb,'exclusions','[]'::jsonb); end if;
 select count(*) filter(where rr.source_kind is distinct from 'official'),count(*) filter(where rr.source_kind='official' and (j.seccion_code is null or j.circuito_code is null or j.establecimiento_code is null or j.mesa_code is null)) into non_official_total,incomplete_lineage_total
 from public.result_row rr join public.jurisdiction j on j.id=rr.jurisdiction_id
 where ((j.seccion_code is not null and exists(select 1 from unnest(scope_districts,scope_sections) s(distrito_code,seccion_code) where (s.distrito_code,s.seccion_code)=(j.distrito_code,j.seccion_code))) or (j.seccion_code is null and p_distrito_code is not null and j.distrito_code=p_distrito_code))
  and (p_election_id is null or rr.election_id=p_election_id) and (p_category_id is null or rr.category_id=p_category_id) and (p_distrito_code is null or j.distrito_code=p_distrito_code) and (p_seccion_code is null or j.seccion_code=p_seccion_code or j.seccion_code is null) and (p_circuito_code is null or j.circuito_code=p_circuito_code) and (p_establecimiento_code is null or j.establecimiento_code=p_establecimiento_code);
 exclusions:=(case when non_official_total>0 then jsonb_build_array(jsonb_build_object('reason','non_official_source_rows','rows',non_official_total)) else '[]'::jsonb end)||(case when incomplete_lineage_total>0 then jsonb_build_array(jsonb_build_object('reason','official_rows_with_incomplete_lineage','rows',incomplete_lineage_total)) else '[]'::jsonb end);
 with options as materialized (
  select e.id election_id,e.year,e.round,c.id category_id,c.name category_name,j.distrito_code,case when count(distinct nullif(btrim(j.distrito_name),''))=1 then max(nullif(btrim(j.distrito_name),'')) end distrito_name,case count(distinct nullif(btrim(j.distrito_name),'')) when 0 then 'missing' when 1 then 'present' else 'conflict' end distrito_name_status,count(distinct nullif(btrim(j.distrito_name),'')) distrito_name_variant_count,j.seccion_code,case when count(distinct nullif(btrim(j.seccion_name),''))=1 then max(nullif(btrim(j.seccion_name),'')) end seccion_name,case count(distinct nullif(btrim(j.seccion_name),'')) when 0 then 'missing' when 1 then 'present' else 'conflict' end seccion_name_status,count(distinct nullif(btrim(j.seccion_name),'')) seccion_name_variant_count
  from unnest(scope_districts,scope_sections) scope(distrito_code,seccion_code) join public.jurisdiction j using(distrito_code,seccion_code) join public.result_row rr on rr.jurisdiction_id=j.id and rr.source_kind='official' join public.election e on e.id=rr.election_id join public.category c on c.id=rr.category_id where j.seccion_code is not null and (p_election_id is null or e.id=p_election_id) and (p_category_id is null or c.id=p_category_id) and (p_distrito_code is null or j.distrito_code=p_distrito_code) and (p_seccion_code is null or j.seccion_code=p_seccion_code) group by e.id,e.year,e.round,c.id,c.name,j.distrito_code,j.seccion_code
 ), counted as (select count(*) total from options), page as (select * from options order by year,round,election_id,category_name,category_id,distrito_code,seccion_code limit 200)
 select counted.total,coalesce(jsonb_agg(to_jsonb(page) order by page.year,page.round,page.election_id,page.category_name,page.category_id,page.distrito_code,page.seccion_code) filter(where page.election_id is not null),'[]'::jsonb) into facet_total,facet_page from counted left join page on true group by counted.total;
 if p_election_id is not null and p_category_id is not null and p_distrito_code is not null and p_seccion_code is not null then
  with options as materialized (select p_election_id election_id,p_category_id category_id,j.distrito_code,j.seccion_code,j.circuito_code,case when count(distinct nullif(btrim(j.circuito_name),''))=1 then max(nullif(btrim(j.circuito_name),'')) end circuito_name,case count(distinct nullif(btrim(j.circuito_name),'')) when 0 then 'missing' when 1 then 'present' else 'conflict' end circuito_name_status,count(distinct nullif(btrim(j.circuito_name),'')) circuito_name_variant_count from public.result_row rr join public.jurisdiction j on j.id=rr.jurisdiction_id where rr.source_kind='official' and rr.election_id=p_election_id and rr.category_id=p_category_id and (j.distrito_code,j.seccion_code)=(p_distrito_code,p_seccion_code) and j.circuito_code is not null group by j.distrito_code,j.seccion_code,j.circuito_code), counted as (select count(*) total from options), page as (select * from options order by circuito_code limit 200) select counted.total,coalesce(jsonb_agg(to_jsonb(page) order by page.circuito_code) filter(where page.circuito_code is not null),'[]') into circuit_total,circuit_page from counted left join page on true group by counted.total;
 end if;
 if p_circuito_code is not null then
  with options as materialized (select p_election_id election_id,p_category_id category_id,j.distrito_code,j.seccion_code,j.circuito_code,j.establecimiento_code,case when count(distinct nullif(btrim(j.establecimiento_name),''))=1 then max(nullif(btrim(j.establecimiento_name),'')) end establecimiento_name,case count(distinct nullif(btrim(j.establecimiento_name),'')) when 0 then 'missing' when 1 then 'present' else 'conflict' end establecimiento_name_status,count(distinct nullif(btrim(j.establecimiento_name),'')) establecimiento_name_variant_count from public.result_row rr join public.jurisdiction j on j.id=rr.jurisdiction_id where rr.source_kind='official' and rr.election_id=p_election_id and rr.category_id=p_category_id and (j.distrito_code,j.seccion_code,j.circuito_code)=(p_distrito_code,p_seccion_code,p_circuito_code) and j.establecimiento_code is not null group by j.distrito_code,j.seccion_code,j.circuito_code,j.establecimiento_code), counted as (select count(*) total from options), page as (select * from options order by establecimiento_code limit 200) select counted.total,coalesce(jsonb_agg(to_jsonb(page) order by page.establecimiento_code) filter(where page.establecimiento_code is not null),'[]') into establishment_total,establishment_page from counted left join page on true group by counted.total;
 end if;
 if p_establecimiento_code is not null then
  with options as materialized (select distinct p_election_id election_id,p_category_id category_id,j.distrito_code,j.seccion_code,j.circuito_code,j.establecimiento_code,j.mesa_code from public.result_row rr join public.jurisdiction j on j.id=rr.jurisdiction_id where rr.source_kind='official' and rr.election_id=p_election_id and rr.category_id=p_category_id and (j.distrito_code,j.seccion_code,j.circuito_code,j.establecimiento_code)=(p_distrito_code,p_seccion_code,p_circuito_code,p_establecimiento_code) and j.mesa_code is not null), counted as (select count(*) total from options), page as (select * from options order by mesa_code limit 200) select counted.total,coalesce(jsonb_agg(to_jsonb(page) order by page.mesa_code) filter(where page.mesa_code is not null),'[]') into mesa_total,mesa_page from counted left join page on true group by counted.total;
 end if;
 if greatest(facet_total,circuit_total,establishment_total,mesa_total)>200 then
  overflow_exclusions:=(case when facet_total>200 then jsonb_build_array(jsonb_build_object('reason','coarse_facets_overflow','rows',facet_total)) else '[]'::jsonb end)||(case when circuit_total>200 then jsonb_build_array(jsonb_build_object('reason','circuitos_overflow','rows',circuit_total)) else '[]'::jsonb end)||(case when establishment_total>200 then jsonb_build_array(jsonb_build_object('reason','establecimientos_overflow','rows',establishment_total)) else '[]'::jsonb end)||(case when mesa_total>200 then jsonb_build_array(jsonb_build_object('reason','mesas_overflow','rows',mesa_total)) else '[]'::jsonb end);
  return jsonb_build_object('status','payload_too_large','facets','[]'::jsonb,'total',greatest(facet_total,circuit_total,establishment_total,mesa_total),'truncated',true,'circuitos','[]'::jsonb,'establecimientos','[]'::jsonb,'mesas','[]'::jsonb,'exclusions',overflow_exclusions);
 end if;
 return jsonb_build_object('status','ok','facets',facet_page,'total',facet_total,'truncated',false,'circuitos',circuit_page,'establecimientos',establishment_page,'mesas',mesa_page,'exclusions',exclusions);
end $$;
revoke all on function workspace_api.official_facets(uuid,uuid,text,text,text,text) from public,anon,authenticated;
grant execute on function workspace_api.official_facets(uuid,uuid,text,text,text,text) to authenticated;
reset role;
revoke create on schema workspace_api from workspace_query_owner;
do $$ begin if to_regrole('service_role') is not null then revoke all on function workspace_api.official_facets(uuid,uuid,text,text,text,text) from service_role; end if; end $$;
do $$ begin if current_setting('votus_drilldown_facets.workspace_query_owner',true)='false' then execute format('revoke workspace_query_owner from %I',current_user); end if; end $$;
commit;
