begin;
do $$ declare r text; begin foreach r in array array['workspace_admin_owner','workspace_review_ingest_owner'] loop perform set_config('votus_review_scope_down.'||r,pg_has_role(current_user,r,'SET')::text,true); if not pg_has_role(current_user,r,'SET') then execute format('grant %I to %I',r,current_user); end if; end loop; end $$;
do $$ declare scoped bigint; begin select count(*) into scoped from public.review_item where tenant_scope_state='section_scoped'; raise notice 'structured review rollback preserves % review item(s) as platform-only and removes their tenant scope',scoped; end $$;
drop trigger review_item_scope_state_on_item on public.review_item;
drop trigger review_item_scope_state_on_scope on workspace_private.review_item_section_scope;
drop policy workspace_review_ingest_owner_review_select on public.review_item;
drop policy workspace_review_ingest_owner_review_insert on public.review_item;
set role workspace_admin_owner;
drop policy workspace_review_ingest_owner_section_select on workspace_private.section_scope;
revoke select,references on workspace_private.section_scope from workspace_review_ingest_owner;
reset role;
set role workspace_review_ingest_owner;
drop function workspace_private.record_review_item(text,text,text,text,text[],text[]);
drop function workspace_private.enforce_review_item_scope_state();
drop table workspace_private.review_item_section_scope;
reset role;
alter table public.review_item drop constraint review_item_tenant_scope_state_check;
alter table public.review_item drop column tenant_scope_state;
revoke select,insert,references,trigger on public.review_item from workspace_review_ingest_owner;
grant insert,update,delete on public.review_item to etl_writer;
revoke usage on schema workspace_private from etl_writer;
do $$ declare r text; begin foreach r in array array['workspace_review_ingest_owner','workspace_admin_owner'] loop if current_setting('votus_review_scope_down.'||r,true)='false' then execute format('revoke %I from %I',r,current_user); end if; end loop; end $$;
commit;
