import type { ReactElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ facets: vi.fn(), evidence: vi.fn() }));
vi.mock("@/lib/workspace/official-facets", () => ({ AuthorizedOfficialFacetsError: class AuthorizedOfficialFacetsError extends Error {}, OFFICIAL_FACETS_ERROR: { AUTHORIZATION_DENIED: "authorization_denied" }, createAuthorizedOfficialFacetRepository: () => ({ facets: mocks.facets }) }));
vi.mock("@/lib/workspace/official-comparison-evidence", () => ({ OFFICIAL_COMPARISON_EVIDENCE_STATUS: { OK: "ok", EMPTY: "empty", AUTHORIZATION_DENIED: "authorization_denied", UNAVAILABLE: "unavailable", PAYLOAD_TOO_LARGE: "payload_too_large", MALFORMED: "malformed" }, loadAuthorizedOfficialComparisonEvidence: mocks.evidence }));
const { default: ComparePage } = await import("./page");
const IDS = { leftElection: "10000000-0000-4000-8000-000000000001", rightElection: "10000000-0000-4000-8000-000000000002", leftCategory: "20000000-0000-4000-8000-000000000001", rightCategory: "20000000-0000-4000-8000-000000000002" } as const;
const PARAMS = { leftElectionId: IDS.leftElection, leftCategoryId: IDS.leftCategory, rightElectionId: IDS.rightElection, rightCategoryId: IDS.rightCategory, distritoCode: "02", seccionCode: "027" };
const elections = [{ id: IDS.leftElection, year: 2023, round: "generales", label: "2023 generales" }, { id: IDS.rightElection, year: 2025, round: "generales", label: "2025 generales" }, { id: "10000000-0000-4000-8000-000000000003", year: 2021, round: "generales", label: "2021 generales" }];
const district = { code: "02", name: "Buenos Aires", nameStatus: "present" as const, nameVariantCount: 1 }, section = { code: "027", name: "Coronel Rosales", nameStatus: "present" as const, nameVariantCount: 1 };
function facets(selection: Record<string, string | undefined>) { const left = selection.electionId === IDS.leftElection, right = selection.electionId === IDS.rightElection; return { elections, categories: left ? [{ id: IDS.leftCategory, name: "DIPUTADOS 2023" }] : right ? [{ id: IDS.rightCategory, name: "DIPUTADOS 2025" }] : [], distritos: selection.categoryId ? [district] : [], secciones: selection.distritoCode ? [section] : [], circuitos: [], establecimientos: [], mesas: [], availableLevels: selection.seccionCode ? ["distrito", "seccion"] : [], exclusions: [] }; }
function side(year: 2023 | 2025, electionId: string, categoryId: string, votes: readonly [number, number]) { const archiveEntryId = `official/archive-${year}`, total = votes[0] + votes[1]; return { result: { status: "ok" as const, sourceKind: "official" as const, level: "seccion" as const, sourceGranularity: "mesa" as const, electionYear: year, electionRound: "generales", totalVotes: total, mesaCount: 1, parties: [{ identityStatus: "canonical" as const, canonicalPartyId: "party-a", displayName: year === 2023 ? "PARTIDO A 2023" : "PARTIDO A 2025", listId: null, votes: votes[0], voteShare: String(votes[0] / total) }, { identityStatus: "canonical" as const, canonicalPartyId: "party-b", displayName: year === 2023 ? "PARTIDO B 2023" : "PARTIDO B 2025", listId: null, votes: votes[1], voteShare: String(votes[1] / total) }], archiveEntryIds: [archiveEntryId], sourceAudit: [{ kind: "official", rows: 2, votes: total }], sourceExclusions: [{ kind: "fiscalizacion", rows: 1, votes: 999 }] }, reference: { items: [{ jurisdictionId: `${year}-section`, electionId, year, round: "generales", categoryId, categoryName: `DIPUTADOS ${year}`, distritoCode: "02", distritoName: "Buenos Aires", seccionCode: "027", seccionName: "Coronel Rosales", circuitoCode: null, circuitoName: null, establecimientoCode: null, establecimientoName: null, mesaCode: null }], sourceExclusions: [{ kind: "fiscalizacion", reason: "non_official_source" as const, rows: 1 }] }, provenance: { items: [{ archiveEntryId, capability: "national", mime: "text/csv", bytes: 120, fetchedAt: "2026-01-01T00:00:00Z", status: "ok" as const, sha256: "a".repeat(64) }], sourceExclusions: [{ kind: "fiscalizacion", rows: 1, votes: 999 }] } }; }
function evidence() { return { status: "ok" as const, left: side(2023, IDS.leftElection, IDS.leftCategory, [60, 40]), right: side(2025, IDS.rightElection, IDS.rightCategory, [55, 45]) }; }
beforeEach(() => { mocks.facets.mockReset().mockImplementation(facets); mocks.evidence.mockReset().mockResolvedValue(evidence()); }); afterEach(() => vi.clearAllMocks());
async function render(params: Record<string, string | string[] | undefined>): Promise<string> { return renderToStaticMarkup((await ComparePage({ searchParams: Promise.resolve(params) })) as ReactElement); }
describe("authorized comparison page", () => {
  it("loads authorized facets for independent sides and one shared exact section", async () => { const markup = await render({}); for (const name of ["leftElectionId", "rightElectionId", "leftCategoryId", "rightCategoryId", "distritoCode", "seccionCode"]) expect(markup).toContain(`name="${name}"`); expect(markup).toContain('<form action="/compare" method="get">'); expect(markup).toContain("2023 generales"); expect(markup).toContain("2025 generales"); expect(markup).not.toContain("2021 generales"); expect(mocks.facets).toHaveBeenCalledTimes(1); expect(mocks.evidence).not.toHaveBeenCalled(); await render({ leftElectionId: IDS.leftElection, rightElectionId: IDS.rightElection }); expect(mocks.facets).toHaveBeenCalledWith({ electionId: IDS.leftElection }); expect(mocks.facets).toHaveBeenCalledWith({ electionId: IDS.rightElection }); });
  it("renders canonical swing figures and URL-free provenance from the all-or-nothing evidence", async () => { const markup = await render(PARAMS); expect(mocks.evidence).toHaveBeenCalledWith(expect.objectContaining({ electionId: IDS.leftElection, categoryId: IDS.leftCategory, distritoCode: "02", seccionCode: "027", requestedLevel: "seccion" }), expect.objectContaining({ electionId: IDS.rightElection, categoryId: IDS.rightCategory, distritoCode: "02", seccionCode: "027", requestedLevel: "seccion" })); for (const text of ["PARTIDO A 2023", "PARTIDO A 2025", "60,00 %", "55,00 %", "-5,00 puntos porcentuales", "official/archive-2023", "official/archive-2025", "SHA-256"]) expect(markup).toContain(text); expect(markup).not.toMatch(/https?:\/\//); expect(markup).not.toContain("/private/"); expect(markup).not.toContain("999 votos"); });
  it("refuses a D6 source-granularity mismatch without any figures", async () => { const value = evidence(); Object.assign(value.right.result, { sourceGranularity: "distrito" as const }); mocks.evidence.mockResolvedValue(value); const markup = await render(PARAMS); for (const text of ["Granularidad mixta", "mesa", "distrito"]) expect(markup).toContain(text); expect(markup).not.toContain("puntos porcentuales"); expect(markup).not.toContain("official/archive-2023"); });
  it.each([["authorization_denied", "No tiene autorización"], ["payload_too_large", "excede el límite seguro"], ["malformed", "no superó la validación"], ["unavailable", "no está disponible"]] as const)("renders no figures for %s evidence", async (status, message) => { mocks.evidence.mockResolvedValue({ status }); const markup = await render(PARAMS); expect(markup).toContain(message); expect(markup).not.toContain("puntos porcentuales"); expect(markup).not.toContain("official/archive"); });
  it.each([["repeated", { ...PARAMS, leftElectionId: [IDS.leftElection, IDS.rightElection] }], ["legacy", { ...PARAMS, election2023: IDS.leftElection }], ["unknown", { ...PARAMS, debug: "true" }]])("rejects %s query keys before authorized reads", async (_case, params) => { const markup = await render(params); expect(markup).toContain("Se rechazó la solicitud"); expect(mocks.facets).not.toHaveBeenCalled(); expect(mocks.evidence).not.toHaveBeenCalled(); });
  it("hides authorized facet provider failures", async () => { mocks.facets.mockRejectedValue(new Error("private provider detail")); const markup = await render({}); expect(markup).toContain("No se pudieron cargar las opciones autorizadas"); expect(markup).not.toContain("private provider detail"); });
});
