import "server-only"; import { parseOfficialExploration, type ExplorationOk } from "@/lib/results/exploration-contract"; import { EXPLORATION_LEVEL } from "@/lib/results/exploration";
import { createSupabaseServerClient } from "@/lib/supabase/server-client"; import { authorizedOfficialBundle } from "@/lib/workspace/context";
export const MUNICIPAL_2023_ARCHIVE = { id: "national/2023-generales", sha256: "2562b18c741ba5740d264e5328f206cb25f709ed0a4f8cf962f301e423e79c6b" } as const; const MUNICIPAL_SCOPE = { distritoCode: "02", seccionCode: "027" } as const; const MUNICIPAL_IDENTITIES = { 2025: { year: 2025, round: "provinciales", categoryName: "CONCEJALES" }, 2023: { year: 2023, round: "generales", categoryName: "INTENDENTE" } } as const; export type MunicipalYear = keyof typeof MUNICIPAL_IDENTITIES; export const MUNICIPAL_JURISDICTION_ID = `${MUNICIPAL_SCOPE.distritoCode}/${MUNICIPAL_SCOPE.seccionCode}`; const OFFICIAL_FACADE_ITEM_LIMIT = 100, OFFICIAL_REFERENCE_ITEM_LIMIT = 200, OFFICIAL_FACADE_EXCLUSION_LIMIT = 20, MUNICIPAL_ATTRIBUTABLE_ARCHIVE_COUNT = 1; // 20260826200000/20260827000000 bounds; ResultRow attributes exactly one archive.
export const MUNICIPAL_EVIDENCE_STATUS = { OK: "ok", EMPTY: "empty", DENIED: "denied", UNAVAILABLE: "unavailable", MALFORMED: "malformed", TRUNCATED: "truncated" } as const; export interface OfficialProvenanceMetadata { archiveEntryId: string; sha256: string | null; fetchedAt: string; status: string }
interface MunicipalOfficialEvidenceOk { status: typeof MUNICIPAL_EVIDENCE_STATUS.OK; result: ExplorationOk; provenance: OfficialProvenanceMetadata[] } interface MunicipalOfficialEvidenceState { status: Exclude<(typeof MUNICIPAL_EVIDENCE_STATUS)[keyof typeof MUNICIPAL_EVIDENCE_STATUS], typeof MUNICIPAL_EVIDENCE_STATUS.OK> } export type MunicipalOfficialEvidence = MunicipalOfficialEvidenceOk | MunicipalOfficialEvidenceState; const record = (value: unknown): Record<string, unknown> | null => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; const integer = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value >= 0, bounded = (value: unknown, limit: number): unknown[] | null => Array.isArray(value) && value.length <= limit ? value : null;
function explicitState(parts: Record<string, unknown>[]): MunicipalOfficialEvidenceState | null { if (parts.some((part) => part["truncated"] === true || part["status"] === "payload_too_large")) return { status: MUNICIPAL_EVIDENCE_STATUS.TRUNCATED }; if (parts.some((part) => part["status"] === "authorization_denied")) return { status: MUNICIPAL_EVIDENCE_STATUS.DENIED };
  if (parts.some((part) => part["authorization_status"] !== "authorized")) return { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED }; if (parts.some((part) => part["status"] === "source_unavailable" || part["status"] === "selection_invalid")) return { status: MUNICIPAL_EVIDENCE_STATUS.UNAVAILABLE }; return null;
} function safeReference(value: Record<string, unknown>, electionId: string, categoryId: string, year: MunicipalYear): boolean {
  const items = bounded(value["items"], OFFICIAL_REFERENCE_ITEM_LIMIT); if (!items || value["status"] !== "ok" || value["source_kind"] !== "official" || !integer(value["total"]) || value["total"] === 0 || value["total"] !== items.length) return false;
  return items.every((item) => { const ref = record(item); return ref !== null && ref["election_id"] === electionId && ref["category_id"] === categoryId && ref["year"] === year && ref["category_name"] === MUNICIPAL_IDENTITIES[year].categoryName && ref["distrito_code"] === MUNICIPAL_SCOPE.distritoCode && ref["seccion_code"] === MUNICIPAL_SCOPE.seccionCode; });
} function safeProvenance(value: Record<string, unknown>, expectedIds: string[]): OfficialProvenanceMetadata[] | null {
  const ids = bounded(value["archive_entry_ids"], OFFICIAL_FACADE_ITEM_LIMIT), sources = bounded(value["sources"], OFFICIAL_FACADE_ITEM_LIMIT); if (!ids || !sources || value["status"] !== "ok" || value["source_kind"] !== "official" || !integer(value["total"]) || value["total"] === 0 || value["total"] !== ids.length || ids.length !== sources.length || !ids.every((id): id is string => typeof id === "string" && id.length > 0) || new Set(ids).size !== ids.length || [...ids].sort().join("\0") !== [...expectedIds].sort().join("\0")) return null;
  const clean = sources.map((source, index) => { const item = record(source); if (!item || item["metadata_status"] !== "available" || item["id"] !== ids[index] || (item["sha256"] !== null && (typeof item["sha256"] !== "string" || !/^[0-9a-f]{64}$/.test(item["sha256"]))) || typeof item["fetched_at"] !== "string" || !Number.isFinite(Date.parse(item["fetched_at"])) || typeof item["status"] !== "string" || item["status"].length === 0) return null; return { archiveEntryId: item["id"] as string, sha256: item["sha256"] as string | null, fetchedAt: item["fetched_at"], status: item["status"] }; }); return clean.every((item) => item !== null) ? clean as OfficialProvenanceMetadata[] : null; }
export async function sanitizeMunicipalOfficialBundle(payload: unknown, electionId: string, categoryId: string, year: MunicipalYear = 2025): Promise<MunicipalOfficialEvidence> { const bundle = record(payload), result = record(bundle?.["result"]), reference = record(bundle?.["reference"]), provenance = record(bundle?.["provenance"]); if (!bundle || !result || !reference || !provenance) return { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED }; const state = explicitState([result, reference, provenance]); if (state) return state;
  if (result["status"] === "no_rows" && result["source_kind"] === "official" && reference["status"] === "no_rows" && reference["source_kind"] === "official" && provenance["status"] === "no_rows" && provenance["source_kind"] === "official" && reference["total"] === 0 && reference["truncated"] === false && Array.isArray(reference["items"]) && reference["items"].length === 0 && provenance["truncated"] === false && (!("total" in provenance) || provenance["total"] === 0) && (!("archive_entry_ids" in provenance) || Array.isArray(provenance["archive_entry_ids"]) && provenance["archive_entry_ids"].length === 0) && (!("sources" in provenance) || Array.isArray(provenance["sources"]) && provenance["sources"].length === 0) && (!("total" in result) || result["total"] === 0) && (!("parties" in result) || Array.isArray(result["parties"]) && result["parties"].length === 0)) return { status: MUNICIPAL_EVIDENCE_STATUS.EMPTY }; const parties = bounded(result["parties"], OFFICIAL_FACADE_ITEM_LIMIT), audits = bounded(result["source_audit"], OFFICIAL_FACADE_EXCLUSION_LIMIT), exclusions = bounded(result["source_exclusions"], OFFICIAL_FACADE_EXCLUSION_LIMIT), ids = bounded(result["archive_entry_ids"], OFFICIAL_FACADE_ITEM_LIMIT);
  if (!parties || !audits || !exclusions || !ids || ids.length !== MUNICIPAL_ATTRIBUTABLE_ARCHIVE_COUNT || new Set(ids).size !== ids.length || !ids.every((id): id is string => typeof id === "string" && id.length > 0) || !safeReference(reference, electionId, categoryId, year)) return { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED };
  try { const parsed = parseOfficialExploration(result), partyVotes = parsed.status === "ok" ? parsed.parties.reduce((sum, party) => sum + party.votes, 0) : 0; if (parsed.status !== "ok" || parsed.electionYear !== MUNICIPAL_IDENTITIES[year].year || parsed.electionRound !== MUNICIPAL_IDENTITIES[year].round || parsed.categoryName !== MUNICIPAL_IDENTITIES[year].categoryName || parsed.level !== EXPLORATION_LEVEL.SECCION || new Set(parsed.sourceExclusions.map(({ kind }) => kind)).size !== parsed.sourceExclusions.length || parsed.sourceAudit.length !== 1 || parsed.sourceAudit[0]?.kind !== "official" || parsed.sourceAudit[0].rows <= 0 || parsed.sourceAudit[0].votes !== parsed.totalVotes || !Number.isSafeInteger(partyVotes) || partyVotes !== parsed.totalVotes) return { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED }; const clean = safeProvenance(provenance, parsed.archiveEntryIds); return clean && (year !== 2023 || clean.length === 1 && clean[0]?.archiveEntryId === MUNICIPAL_2023_ARCHIVE.id && clean[0]?.sha256 === MUNICIPAL_2023_ARCHIVE.sha256 && clean[0]?.status === "ok") ? { status: MUNICIPAL_EVIDENCE_STATUS.OK, result: parsed, provenance: clean } : { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED }; } catch { return { status: MUNICIPAL_EVIDENCE_STATUS.MALFORMED }; } }
export async function loadMunicipalOfficialEvidence(year: MunicipalYear = 2025): Promise<MunicipalOfficialEvidence> { const electionId = year === 2023 ? process.env["MUNICIPAL_2023_ELECTION_ID"] : process.env["MUNICIPAL_ELECTION_ID"], categoryId = year === 2023 ? process.env["MUNICIPAL_2023_CATEGORY_ID"] : process.env["MUNICIPAL_CATEGORY_ID"]; if (!electionId || !categoryId) return { status: MUNICIPAL_EVIDENCE_STATUS.UNAVAILABLE };
  try { const payload = await authorizedOfficialBundle(await createSupabaseServerClient(), { electionId, categoryId, ...MUNICIPAL_SCOPE, circuitoCode: null, establecimientoCode: null, mesaCode: null, requestedLevel: EXPLORATION_LEVEL.SECCION }); return sanitizeMunicipalOfficialBundle(payload, electionId, categoryId, year); } catch { return { status: MUNICIPAL_EVIDENCE_STATUS.UNAVAILABLE }; } }
